//! SSH SOCKS5 tunnel import.
//!
//! Generates houdinny tunnel config entries for SSH-based SOCKS5 proxies.
//! Optionally starts the SSH tunnels in the background via `ssh -D <port> -N -f`.

use std::path::Path;

use anyhow::{Context, Result};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate SSH SOCKS5 tunnel config entries and optionally start the tunnels.
///
/// For each port in `ports`, a `[[tunnel]]` entry with `protocol = "socks5"`
/// is created pointing at `127.0.0.1:<port>`.
///
/// When `start` is `true`, each tunnel is started in the background with:
/// ```text
/// ssh -D <port> -N -f <user>@<host>
/// ```
///
/// If `output` already exists, new entries are appended. Otherwise a fresh
/// config file is created with a default `[proxy]` section.
pub async fn import_ssh(
    host: &str,
    user: &str,
    ports: &[u16],
    output: &Path,
    start: bool,
) -> Result<()> {
    if ports.is_empty() {
        anyhow::bail!("no ports specified — need at least one SOCKS5 port");
    }

    // Optionally start SSH tunnels.
    if start {
        for &port in ports {
            start_ssh_tunnel(user, host, port).await?;
        }
    }

    // Generate TOML entries.
    let toml_block = generate_toml(host, ports);

    // Write / append to the output file.
    write_config(output, &toml_block)?;

    tracing::info!(
        count = ports.len(),
        path = %output.display(),
        "added SSH SOCKS5 tunnels"
    );
    println!(
        "Added {} SSH SOCKS5 tunnel(s) to {}",
        ports.len(),
        output.display()
    );

    if start {
        println!("Started {} SSH tunnel(s) to {}@{}", ports.len(), user, host);
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Start a single SSH SOCKS5 tunnel in the background.
async fn start_ssh_tunnel(user: &str, host: &str, port: u16) -> Result<()> {
    tracing::info!(user, host, port, "starting SSH SOCKS5 tunnel");

    let status = tokio::process::Command::new("ssh")
        .args([
            "-D",
            &port.to_string(),
            "-N",
            "-f",
            &format!("{user}@{host}"),
        ])
        .status()
        .await
        .with_context(|| format!("failed to execute ssh -D {port} -N -f {user}@{host}"))?;

    if !status.success() {
        anyhow::bail!("ssh -D {port} -N -f {user}@{host} exited with status {status}");
    }

    tracing::debug!(port, "SSH tunnel started");
    Ok(())
}

/// Generate TOML `[[tunnel]]` blocks for SSH SOCKS5 tunnels.
pub fn generate_toml(host: &str, ports: &[u16]) -> String {
    let mut buf = String::new();
    buf.push_str("# Generated by: houdinny import ssh\n");

    for &port in ports {
        let label = format!("ssh-{host}-{port}");
        buf.push('\n');
        buf.push_str("[[tunnel]]\n");
        buf.push_str("protocol = \"socks5\"\n");
        buf.push_str(&format!("address = \"127.0.0.1:{port}\"\n"));
        buf.push_str(&format!("label = \"{label}\"\n"));
    }

    buf
}

/// Write or append tunnel config to the output file.
fn write_config(output: &Path, toml_block: &str) -> Result<()> {
    use std::fs;
    use std::io::Write;

    if output.exists() {
        // Append to existing file.
        let mut file = fs::OpenOptions::new()
            .append(true)
            .open(output)
            .with_context(|| format!("failed to open {} for appending", output.display()))?;
        // Ensure we start on a new line.
        writeln!(file)?;
        write!(file, "{toml_block}")?;
    } else {
        // Create a fresh config with a default [proxy] section.
        let mut contents = String::new();
        contents.push_str("# houdinny tunnel configuration\n");
        contents.push_str("# Generated by: houdinny import ssh\n\n");
        contents.push_str("[proxy]\n");
        contents.push_str("listen = \"127.0.0.1:8080\"\n");
        contents.push_str("mode = \"transparent\"\n");
        contents.push_str("strategy = \"random\"\n\n");
        contents.push_str(toml_block);

        fs::write(output, contents)
            .with_context(|| format!("failed to write {}", output.display()))?;
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_toml_single_port() {
        let toml = generate_toml("my-tailscale-host", &[1080]);
        assert!(toml.contains("protocol = \"socks5\""));
        assert!(toml.contains("address = \"127.0.0.1:1080\""));
        assert!(toml.contains("label = \"ssh-my-tailscale-host-1080\""));
    }

    #[test]
    fn generate_toml_multiple_ports() {
        let toml = generate_toml("bastion", &[1080, 1081, 1082]);
        assert_eq!(toml.matches("[[tunnel]]").count(), 3);
        assert!(toml.contains("address = \"127.0.0.1:1080\""));
        assert!(toml.contains("address = \"127.0.0.1:1081\""));
        assert!(toml.contains("address = \"127.0.0.1:1082\""));
        assert!(toml.contains("label = \"ssh-bastion-1080\""));
        assert!(toml.contains("label = \"ssh-bastion-1081\""));
        assert!(toml.contains("label = \"ssh-bastion-1082\""));
    }

    #[test]
    fn generate_toml_empty_ports() {
        let toml = generate_toml("host", &[]);
        assert!(toml.contains("# Generated by: houdinny import ssh"));
        assert!(!toml.contains("[[tunnel]]"));
    }

    #[test]
    fn write_config_creates_new_file() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("tunnels.toml");

        let toml_block = "[[tunnel]]\nprotocol = \"socks5\"\nlabel = \"test\"\n";
        write_config(&path, toml_block).expect("should write");

        let contents = std::fs::read_to_string(&path).expect("read");
        assert!(contents.contains("[proxy]"));
        assert!(contents.contains("listen = \"127.0.0.1:8080\""));
        assert!(contents.contains("[[tunnel]]"));
        assert!(contents.contains("label = \"test\""));
    }

    #[test]
    fn write_config_appends_to_existing() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("tunnels.toml");

        // Create an initial file.
        std::fs::write(&path, "[proxy]\nlisten = \"0.0.0.0:9090\"\n").expect("write");

        let toml_block = "[[tunnel]]\nprotocol = \"socks5\"\nlabel = \"appended\"\n";
        write_config(&path, toml_block).expect("should append");

        let contents = std::fs::read_to_string(&path).expect("read");
        assert!(contents.contains("listen = \"0.0.0.0:9090\""));
        assert!(contents.contains("label = \"appended\""));
    }

    #[tokio::test]
    async fn import_ssh_empty_ports_errors() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("tunnels.toml");
        let result = import_ssh("host", "user", &[], &path, false).await;
        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .to_string()
                .contains("no ports specified")
        );
    }
}
